name: Auto Pull and Restart Specific IIS Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
	      - name: Pull latest code
        run: |
          $LogPath = "C:/logs/repo-name"
          if (!(Test-Path $LogPath)) { New-Item -ItemType Directory -Path $LogPath }
          $LogFile = "$LogPath/deploy.log"
          Add-Content -Path $LogFile -Value "`n===== Pulling latest code - $(Get-Date) ====="
          run: git -C "E:\test" pull origin main
        shell: powershell
     
      - name: Restart IIS Site via appcmd
        run: |
          & "C:\Windows\System32\inetsrv\appcmd.exe" stop site "msgapi"
          Start-Sleep -Seconds 2
          & "C:\Windows\System32\inetsrv\appcmd.exe" start site "msgapi"
        shell: powershell
