name: Auto Pull and Restart Specific IIS Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code
        run: git -C "E:\test" pull origin main

      - name: Restart IIS Site
        run: Restart-Website -Name "msgapi"
        shell: powershell
